# Config file for [Air](https://github.com/cosmtrek/air) in TOML format
# Air allows us to hot reload our go app when developing

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  # Copy env variables
  cmd = "cp .env ./tmp/.env && go build -o ./tmp/main cmd/youchooseserver/youchooseserver.go"
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000 # ms
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  # Exclude files.
  exclude_file = []
  exclude_regex = ["_test.go"]
  # Exclude unchanged files.
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  # Delay after sending Interrupt signal
  kill_delay = "1s"
  # This log file places in your tmp_dir.
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  # Delete tmp directory on exit; defaults false
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
