services:
  postgres:
    image: postgres:14
    restart: always
    container_name: youchoose_postgres
    healthcheck:
      test: pg_isready -U ${DB_USER}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  my-network:
    driver: bridge
volumes:
  postgres:
